# Generated by Django 5.0.1 on 2024-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Defaultprofile_tvf0tm', upload_to='media/'),
        ),
    ]
